export const GET = 'GET'
export const POST = 'POST'
export const PUT = 'PUT'
export const PATCH = 'PATCH'
export const DELETE = 'DELETE'
export const FETCH_ROOMS = 'FETCH_ROOMS'
export const DELETE_ROOM = 'DELETE_ROOM'
export const UPDATE_ROOM = 'UPDATE_ROOM'
export const SIGN_IN='SIGN_IN'
export const SIGN_UP='SIGN_UP'
export const ADD_ROOM = 'ADD_ROOM'
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE'
export const DEFAULT_IMAGE =
  'https://grassworksmanufacturing.com/wp-content/themes/i3-digital/images/no-image-available.png'
